### ISSUE TITLE
Question: Compatibility with Krastorio 2

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [Xman1109/Atomic_Overhaul#1]
Hello,

Since I did not find the information and there is no way to check it myself, I want to ask. Is there compatibility or incompatibility with the Krastorio 2 mod?

**Comment by Xman1109** [comment]
I will test it as soon as I can, but I think there shouldn't be a problem between both mods.

**Comment by Xman1109** [comment]
I have looked into it and I haven't found any errors.
So it seems fully compatible.

But if you encounter any sort of Bug, then don't hesitate to create a new issue with the label Bug.
