### ISSUE TITLE
K2 + AO centrifuge missing

### ISSUE THREAD

**Issue by Xman1109** [Xman1109/Atomic_Overhaul#10]
### Discussed in https://github.com/Xman1109/Atomic_Overhaul/discussions/9

<div type='discussions-op-text'>

<sup>Originally posted by **josiahwilkinson** July 20, 2022</sup>
Hello,

I am sorry, but I am having some trouble with the mod. I am playing with K2 + AO + Brevven's materials (not sure if they impact this issue). I am unable to create a centrifuge (by hand or assembler), and the tech tree does not show it anywhere as being unlockable. The Uranium Processing tech shows "Base mod > Atomic Overhaul > Krastorio 2" with just the regular uranium processing and fuel cell, but no centrifuge. The Nuclear Power tech (if it's supposed to be there) shows "Base mod > Atomic Overhaul > Krastorio 2 > Titanium > Zirconium". I'm wondering if there is supposed to be a different way to unlock the centrifuge or if there is some wonky mod interaction.
If you could help find the problem, I would greatly appreciate it.

Thank you very much,
Josiah

P.S.
This is my map string so you can see my mods (if that helps):

>>>eNp1UT2IE0EUnucas+aiXLGNIGeQa1fwtLDQ7CiIiGiXxsrJ7uRu
YH/C7CziXXEprlRstNDGa22usxAsAoIoKBxa2Z3YWHga8dBGiDO7mWS
yuXvw3n7zvTffe28WEKBLKLeep9ypkzCLWJxFbsIpQn1PZw77CQlLRB
jog/Kan3S7lJcvHvV5FlA3YVO3azSm0T23TVJZjCWFctpe5qS7wsSUg
rWSCLORzSLK01KRzXgSl3vbISVBmTwm96OchO5dIig3M3OccOpGVJAw
NflKKpJ4SqMq2EyzumCCxGz26SqCU5qaG9RFFi+ngs5ozGV8X4kjq4z
7SWxSCNxXe7u9jQWkfLiOGsOhcol25HMqR9CTlRiB5LRV/JB1Ogg1Lr
darStKCADWnK1rX1YfeVDUnMEjMBgx/bZmrmtwCx+YWtTgvKFzLrffB
iiaCtliVGXjCSiSGyoJ8GD3xebfN9tN+Pf818eb7TsenL3q/BgsbTVl
sqr2PDQOT58oe6lXQVpzxxulPnvw4b2y7x5U1A1HBXxBhv4NC8H8cYk
278vQOIn0aE0t42Do5PZHb/JVg09eeQ/5EBeV+IIKb1XIG44ngwLihx
jwKZ09MSmR95eQOUMw2fCdbvva6F8aZPZHmHuUmEW8z2+oqYbBOHyzx
tPI99yu6hN+hsFSQFXtSa44qYyWKr7zOH9uC01s4KHTj2///A+lmevp
<<<</div>

**Comment by afewvowels** [comment]
I noticed the "se-centrifuge" technology is hidden in your k2-se.lua script.

I'm consolidating a lot of personal changes I've made in a mod (along with changes to the archives in other mods) into a single (pretty!) convoluted modpack and this hidden tech was blocking vulcanite processing from being researched. I tried to puzzle out where the tech prerequisite was modified but was unable to find it. Also I can't explain why this wasn't a problem on my earlier playthroughs with similar mods installed.

Anyways, I really enjoy this mod pack and the production chains it adds especially the new SE resources. Thanks!
