### ISSUE TITLE
[Mod Crashed Game]

### ISSUE THREAD

**Issue by SGZ-Creations** [Xman1109/Atomic_Overhaul#11]
- (Your factorio-current.log/error message here)
![image](https://user-images.githubusercontent.com/59801736/182086284-f7314466-1050-483b-b01a-536b160b8d61.png)
- A list of Mods you are playing with:
[mod-list.txt](https://github.com/Xman1109/Atomic_Overhaul/files/9231514/mod-list.txt)
- Why it crashed?
After 1.2.0 update the mod broke as of missing input ?

**Comment by Xman1109** [comment]
Ok, I see why it crashed.
Fix will be out in a 10min or so.

**Comment by Xman1109** [comment]
Ok, should be fixed now.

**Comment by SGZ-Creations** [comment]
Thanks
