### ISSUE TITLE
k2+se Error

### ISSUE THREAD

**Issue by mirrornight01** [Xman1109/Atomic_Overhaul#12]
Error ModManager.cpp:1558: 模组 "Atomic_Overhaul" 加载失败：__Atomic_Overhaul__/prototypes/compatibility/k2-se.lua:79: attempt to index field '?' (a nil value)
stack traceback:
	__Atomic_Overhaul__/prototypes/compatibility/k2-se.lua:79: in main chunk
	[C]: in function 'require'
	__Atomic_Overhaul__/data-final-fixes.lua:39: in main chunk

**Comment by Xman1109** [comment]
Coan you give me your mod-list?

**Comment by mirrornight01** [comment]
[zero.zip](https://github.com/Xman1109/Atomic_Overhaul/files/9481671/zero.zip)

**Comment by Xman1109** [comment]
Ok, I will try my best to fix it.

**Comment by Xman1109** [comment]
Okay, I can't reproduce the bug, but I have a rough idea why this error may occur…
I will push out an update in the next few minutes, and if it works please tell me, otherwise I need to add the _Can't reproduce_ label.
