### ISSUE TITLE
Crash with Angelindustries

### ISSUE THREAD

**Issue by Silvernova115** [Xman1109/Atomic_Overhaul#19]
11.415 Loading mod angelsindustries 0.4.16 (data-updates.lua)
  11.553 Error ModManager.cpp:1558: Failed to load mod "angelsindustries": __angelsrefining__/prototypes/recipe-builder.lua:217: attempt to compare number with nil
stack traceback:
	__angelsrefining__/prototypes/recipe-builder.lua:217: in function 'add'
	__angelsrefining__/prototypes/recipe-builder.lua:429: in function 'p_merge_item_lists'
	__angelsrefining__/prototypes/recipe-builder.lua:509: in function 'p_result_merge'
	__angelsrefining__/prototypes/recipe-builder.lua:546: in function 'p_copy'
	__angelsrefining__/prototypes/recipe-builder.lua:567: in function 'patch'
	__angelsrefining__/prototypes/override-functions.lua:968: in function 'execute'
	...lsindustries__/prototypes/angels-industries-override.lua:32: in main chunk
	[C]: in function 'require'
	__angelsindustries__/data-updates.lua:5: in main chunk
  11.556 Loading mod core 0.0.0 (data.lua)
  11.948 Checksum for core: 1476961332
  11.990 Error ModManager.cpp:1558: Error in assignID: recipe-category with name 'crafting' does not exist.

Source: default (utility-sprites).
  12.127 Initial atlas bitmap size is 16384
  12.128 Created atlas bitmap 2048x640 [icon, not-compressed, mipmap, linear-minification, linear-magnification, linear-mip-level]
  12.134 Texture processor created (2048). GPU accelerated compression Supported: yes, Enabled: yes/yes. Test passed. YCoCgDXT PSNR: 35.83, BC3 PSNR: 33.82
  12.314 Parallel Sprite Loader initialized (threads: 15)
  12.878 Sprites loaded
  12.905 Generated mipmaps (5) for atlas [0] of size 2048x640   
  12.905 Custom mipmaps uploaded.
  12.911 Factorio initialised
  24.691 Quitting: user-quit.
  24.806 Steam API shutdown.
  24.809 Goodbye

error only occurs when atomicoverhaul is enabled

**Comment by Xman1109** [comment]
Very weird...
I will take a look at it, but I can't promise that I'll be able to fix it.

**Comment by Xman1109** [comment]
So…
I had forwarded this issue to the Angels Mods Repo.
Today I got an update on that, in which they fixed the issue.
I don't know when they will make an update to the mod, but if it takes long, then I'll fix it myself with a new version.
