### ISSUE TITLE
[Game Crash] Error attempting to concatenate global 'recipes'

### ISSUE THREAD

**Issue by afewvowels** [Xman1109/Atomic_Overhaul#20]
Hello, I'm currently getting an error on game start. Looks like it's in data-final-fixes.lua at line 116:

![Factorio Screenshot 2022 09 30 - 21 51 33 45](https://user-images.githubusercontent.com/32456218/193378551-f85bda07-0086-49b1-8a34-2f7acee32c6a.png)

**Comment by Xman1109** [comment]
It looks like some other mod is overwriting the recipes variable, I'll fix it in the next few hours.

**Comment by Xman1109** [comment]
Could you give me your mod list?

**Comment by afewvowels** [comment]
Well if it's a mod compatibility thing it might be a bit of a lost cuase lol. I'll get that list to you here shortly.

**Comment by afewvowels** [comment]
base 1.1.69
Flare Stack 2.2.10
rusty-locale 1.0.16
simhelper 1.1.4
Soundpack-alerts-and-sirens-updated-v1-1 1.0.7
YARM 0.8.207
5dim_core 1.1.13
aai-containers 0.2.11
aai-signal-transmission 0.4.7
aai-vehicles-ironclad 0.6.5
alien-biomes 0.6.7
BigBags 1.0.35
bobinserters 1.1.5
boblibrary 1.1.5
bullet-trails 0.6.2
cargo-ships-graphics 0.1.0
ChangeMapSettings 5.0.1
chest-auto-sort 1.0.0
CleanedConcrete 1.0.2
Command_and_Conquer_RedAlert_Sounds 0.9.0
compaktcircuit 1.0.1
CreativeItems 1.6.0
deadlock-beltboxes-loaders 2.4.2
emoji-signals 0.2.0
flib 0.11.2
FluidMustFlow 1.3.1
grappling-gun 0.3.2
informatron 0.2.3
jetpack 0.3.5
Krastorio2Assets 1.2.0
LogisticRequestManager 1.1.23
MiscLib 0.9.2
nixie-tubes 1.1.3
OreEraser 1.5.6
PlayerLevelling 0.1.1
power-grid-comb 1.1.0
quantum-chests 1.0.2
robot_attrition 0.5.12
safefill 1.0.10
SchallVirtualSignal 1.1.2
shield-projector 0.1.6
show-max-underground-distance 0.0.8
space-exploration-graphics 0.6.12
space-exploration-graphics-2 0.6.1
space-exploration-graphics-3 0.6.1
space-exploration-graphics-4 0.6.2
space-exploration-graphics-5 0.6.1
space-exploration-menu-simulations 0.6.8
stdlib 1.4.7
textplates 0.6.9
TrainModeSwitcher 1.0.5
TrainScheduleSignals 2.1.0
5dim_automation 1.1.1
5dim_battlefield 1.1.7
5dim_botrecaller 1.1.2
5dim_decoration 1.1.0
5dim_enemies 1.1.3
5dim_energy 1.1.3
5dim_equipment 1.1.3
5dim_ logistic 1.1.0
5dim_mining 1.1.3
5dim_nuclear 1.1.1
5dim_resources 1.1.2
5dim_storage 1.1.0
5dim_trains 1.1.1
5dim_transport 1.1.5
aai-industry 0.5.19
bobassembly 1.1.15
boblogistics 1.1.5
bobmining 1.1.3
CircuitHUD-V2 1.3.0
combat-mechanics-overhaul 0.6.22
equipment-gantry 0.1.5
EvenMoreTextPlates 1.2.2
fcpu 0.4.14
PickerAtheneum 1.2.5
PipeVisualizer 1.0.4
sonaxaton-research-queue 0.4.21
StatsGui 1.4.1
Deadlock5Dims 1.1.6
PickerInventoryTools 1.1.15
space-exploration 0.6.86
FlareStack-SE 1.0.5
FluidMustFlowSE 0.0.1
Krastorio2 1.3.6
underground-pipe-pack 1.1.2
UnlimitedProductivity 1.4.3
bzsilicon 0.11.4
bztitanium 1.2.8
cargo-ships 0.1.18
Krastorio2RFAC 2.0.0
miniloader 1.15.6
se-space-trains 0.1.12
space-exploration-postporocess 0.6.18
5dim_compatibility 1.1.14
bzlead 1.2.14
LogisticTrainNetwork 1.17.0
more-miniloaders 1.0.9
bztungsten 0.7.4
LTN_Combinator_Modernized 1.0.13
bzzirconium 0.6.11
copy-paste-recipe-signals-to-combinator 2.0.1
LtnManager 0.4.15
bzfoundry 0.2.7
bzcarbon 0.4.6
bzaluminum 0.4.13
bztin 0.1.6
bzgas 0.1.1
bz-dsr-bridge 0.6.0
bzvery 0.4.0

**Comment by afewvowels** [comment]
Lol it's a lot of mods! I was looking at your mod hoping to find a way to put a power source on a deep spaceship that didn't involve steam turbines lol. It's funny how there's fusion and antimatter reactors in Space Exploration but they just involve making heat to make steam and spin turbines. It's like as humanity we've gone to space and made an internet but we're really just living in a steampunk world still lol.

**Comment by Xman1109** [comment]
Could you send me a savefile with all these mods, then I could simply download it and sync all mods instead of enabling/downloading each one?

I am still thinking about including some sort of RTG (radioisotope thermoelectric generator), but I am very bad at making graphics and animations for entities xD

**Comment by afewvowels** [comment]
Well the stock nuclear reactor just kind of glows and emits steam so I don't think the animations have to be too crazy right? Also wow I just looked at my save file and it's 143 MB. I see why the Space Exploration wiki makes a lot of mentions about trimming surfaces that you're not actively building on!

https://drive.google.com/file/d/1Fc4FyEPy-Sv7ERlRQ__jpOPBKgKMojiw/view?usp=sharing

Also I tweaked a bunch of values in these mods like crafting speed in case you're wondering how I make do with like 4 assemblers making green circuits. I'm really hoping a lot of these mod authors don't push any updates out 🤣

**Comment by Xman1109** [comment]
Animations for the reactor are not thaaaat crazy, but if you want you can take a look in the `steamapps\common\Factorio\data\base\graphics\entity\nuclear-reactor` directory, there you can see all the images that are being used for just the reactor, but I can confidently say, assembly machines are waaaayyyy more complicated.

Btw, feel free to suggest something

**Comment by Xman1109** [comment]
I could not quite reproduce this error, but I think I fixed it, but you will need to try...
Update comes in the next few minutes.

**Comment by GeneralTanker** [comment]
![Atomic Overhaul recipe update crash 10-1-22](https://user-images.githubusercontent.com/69743165/193417880-f8e85535-036e-4493-b198-3a41180f077c.png)

similar mod pack as afewvowels but no 5dim or bob's

**Comment by Xman1109** [comment]
what the hell

**Comment by Xman1109** [comment]
its always weird that I dont get these types of errors even though I copy the exact modpack and the exact settings ._.

**Comment by GeneralTanker** [comment]
[Krastorio2 SE11 23 B.zip](https://github.com/Xman1109/Atomic_Overhaul/files/9690718/Krastorio2.SE11.23.B.zip)
[bzchlorine_0.0.1.zip](https://github.com/Xman1109/Atomic_Overhaul/files/9690719/bzchlorine_0.0.1.zip)

Here is my save I have a couple of private mods not ready to upload.

**Comment by Xman1109** [comment]
![image](https://user-images.githubusercontent.com/72877576/193419981-294aab5f-7af6-48a6-b624-bf67a0ae0668.png)


Seems like everything is working, but to ensure that I am not an Idiot, could you test the version that I uploaded to GitHub?

**Comment by GeneralTanker** [comment]
Did you update your mod to 1.3.3 as well?

**Comment by Xman1109** [comment]
The changes are currently only in this GitHub repo, I deleted the 1.3.3 version from the mod portal due to the bugs

**Comment by GeneralTanker** [comment]
the 1.3.4 github version loads

**Comment by Xman1109** [comment]
Does Everything work as intended?

**Comment by GeneralTanker** [comment]
So far it's working.
