### ISSUE TITLE
Error loading

### ISSUE THREAD

**Issue by 0n0w1c** [Xman1109/Atomic_Overhaul#23]
```Error while applying migration: Atomic Overhaul: 1.3.6.lua

__Atomic_Overhaul__/migrations/1.3.6.lua:6: attempt to index field 'se-delivery-cannon-capsule-iridium' (a nil value)
stack traceback:
	__Atomic_Overhaul__/migrations/1.3.6.lua:6: in main chunk
```
Unfortunately, I have a ton of other mods loaded. My first time attempting to load your mod.

**Comment by Xman1109** [comment]
then try to use the version 1.3.5

**Comment by Xman1109** [comment]
I'll fix in in an hour or something

**Comment by 0n0w1c** [comment]
1.3.5 loads without error

**Comment by Xman1109** [comment]
Version 1.3.7 out now.
The bug should be fixed now, if not then message me again, so I can look into it.

**Comment by 0n0w1c** [comment]
Thank you very much, 1.3.7 loads without error.

**Comment by Xman1109** [comment]
Thank you for bringing it to my attention!
