### ISSUE TITLE
[Bug-Report] Heat Power Furnace reverts to steel furnace when mined by hand or removed by bots

### ISSUE THREAD

**Issue by pyroAvatar91** [Xman1109/Atomic_Overhaul#25]
# Bug Report

## Describe the bug

``` 
Just as described in the title. This means that if I ever want to move my heat powered furnaces or misplace them, I lose them and have to recraft them, which is especially annoying since they can't be hand crafted and take a long time to craft.
```

## How to reproduce

``` 
Place down a Heat powered furnace. Mine it by hand or deleting it with bots. Check inventory and see that you have 1 less heat powered furnace and 1 more steel furnace.
``` 

## Your Idea on how to fix it

```
 Sorry, I have no idea. I would assume this is not intended behavior, but I don't know enough about programming to know where to check the code for the cause of this.
```

## Additional information

``` 
I am playing with quite a few QoL mods and K2 + SE as my primary overhaul mods. Let me know if you need a save file.
```

**Comment by Xman1109** [comment]
Are you sure that you are using the newest version of Atomic Overhaul?

**Comment by pyroAvatar91** [comment]
Yes, I am on version 1.3.7. Here is a link to my save: https://drive.google.com/file/d/1bGzphEc75sUAx0sWPs_huTEah8iZrW0A/view?usp=sharing. I have the heat furnace placed and am standing next to it. You can craft more in the assembling machine nearby if needed.

**Comment by Xman1109** [comment]
I fixed this a couple of versions ago, but for some reason the modified file was not committed.

If everything works fine then I can patch it tomorrow, I will keep you up to date.

**Comment by Xman1109** [comment]
Should be fixed with version 1.3.8 .
Please tell me if it helped.

**Comment by pyroAvatar91** [comment]
This is fixed in my game with your recent update. Thank you!

**Comment by Xman1109** [comment]
Glad I could help!
