### ISSUE TITLE
K2 Heavy rocket launcher 

### ISSUE THREAD

**Issue by GeneralTanker** [Xman1109/Atomic_Overhaul#26]
# Bug Report

## Describe the bug

Atomic Overhaul appears to overwrite K2's changes for the nuclear rocket.  The K2 Heavy rocket launcher is meant to launch those instead.

## How to reproduce

Run Atomic Overhaul with K2

## Your Idea on how to fix it

Fix the ammo type to the correct type and change to the heavy rocket for ingredient.

**Comment by Xman1109** [comment]
Fix will come in the next few days.

**Comment by GeneralTanker** [comment]
Doesn't appear to be fully fix for me. 
[Test 128.zip](https://github.com/Xman1109/Atomic_Overhaul/files/10699870/Test.128.zip)

**Comment by Xman1109** [comment]
I'll look into it.

Last time I updated the mod to make no changes to the atomic bomb, if Krastorio 2 is enabled.
