### ISSUE TITLE
[Bug-Report] Mining des Spaceatomreaktors gibt den BodenAtomreaktor zurück

### ISSUE THREAD

**Issue by Flagran** [Xman1109/Atomic_Overhaul#27]
Hey Xman,

ich bin nun soweit und habe den Spaceatomreaktor geforscht und produziert. jedoch bringt mir das aufnehmen des Gebäudes den normalen zurück. Es schein das das Argument "Mining sapce atomreaktor" den normalen zurückgibt. 

Kannst du das bitte in deinem nächsten update fixen?! oder hast du das schon ? ^^

könntest du bitte auch Thoriumzellen in diesem zulassen. das wäre sehr hilfreich *G*

Grüße

Flagran

**Comment by Xman1109** [comment]
Jo, bin gerade dabei, ich hoffe Mal das ich das morgen schaffe, dann mach ich gleich 2 Bugfixes auf einmal.

**Comment by Flagran** [comment]
Ach sehr schön :) dann kann ich anfangen mein Interstellares Raumschiff für Deepspacetech1 zu bauen. Zur zeit bin ich dabei alle Bottlenecks bei den T4 Spacetechs zu stopfen und Naquium steht in den nachsten Spielstunden (ok Tagen ... ok Wochen ...  -.- später) an :)

**Comment by Xman1109** [comment]
Das mit dem Reaktor hab ich jetzt gefixt, aber wegen der Brennstoffzelle muss ich nochmal gucken, entweder mache ich eine Verbesserte Thorium Zelle, oder ich gucke das man die Standard Thorium Zelle benutzen kann

**Comment by Flagran** [comment]
Super Danke :D Ich hatte gerade vor 2 min das game gestartet und wollte nur schnell auf der modpage nach einem andren mod schauen ... bum .. Update von dir ... okay speichern ... Updaten 👍 

zum Thema der Brennstoffzellen bin ich etwas zwiegespalten. Ich finde die Idee mit den speziellen Brennstoffzellen für das SpaceAKW super und das die leistung auch entsprechend geringer ist wie bei den BodenAKW´s ist auch okay. Nach der Story gesehen ist ein AKW auf einem Raumschiff/Spacestation eben eine kompakte Version. die eben kleinere Brennstoffzellen mit einem speziellen zeroG case benötigt.

Ich hätte gern das man Thorium und eigentlich auch die anderen 3 normalen Brennstoffe (MOX Plutoium und Moderiertes Uran) in eben diese "verbesserte Brennelemente" geben kann und entsprechend weniger Leistung bekommt. 
zb.
10GJ Moderiertes Uran
12GJ Plutonium
14GJ MoX
16GJ Thorium
bei 1/4 der Brennstoffkosten der Bodenbrennstoffzelle, danach würde mit 17GJ die normale Iridiumbrennstoffzelle anfangen. Man verliert Energieinhalt zb 50GJ normales Uranbrenelement gegen 10 GJ SpaceUranbrennelement mit 1/4 der Brennstoffkosten kann diese aber im Weltraum nutzen.

Vieleicht kan mann auch mit zusätzlichen Mats und/oder einer Forschung die das ermöglicht arbeiten. Zb eine Beryliumplatte o. Bleiplatte als extra Material für die extra Abschirmung. 

Was hälst du davon ?!

Grüße
