### ISSUE TITLE
Change empty fuel cell to use steel plate instead of iron plate

### ISSUE THREAD

**Issue by Ldmf** [Xman1109/Atomic_Overhaul#3]
Change emty fuel cell to use steel plate in stad of iron plate if krastorio 2 is presend if it is possebel

![20220514203404_1](https://user-images.githubusercontent.com/15316448/168444249-cc3086dc-b329-44d9-83df-4d2c4fefe244.jpg)

**Comment by Xman1109** [comment]
I could do that, but why should I?
I was planning to add an advanced fuel cell, which would require steel.

Maybe [this](https://languagetool.org/) could help you with your spelling.
