### ISSUE TITLE
[Bug-Report] Broken dependency

### ISSUE THREAD

**Issue by nihilistzsche** [Xman1109/Atomic_Overhaul#30]
# Bug Report

## Describe the bug

The info.json reports that this mod should be incompatible with "PlutoniumEnergy" (note the missing space), but includes a space between Plutonium and Energy making the incompatibility non-functional.  

## Your Idea on how to fix it

Change "! Plutonium Energy" to "! PlutoniumEnergy"

**Comment by Xman1109** [comment]
Fix will be included next version
