### ISSUE TITLE
[Bug-Report] SpaceReaktor nicht platzierbar auf Raumschiffboden

### ISSUE THREAD

**Issue by Flagran** [Xman1109/Atomic_Overhaul#31]
Hey XMan, 

hier ist wieder die Nervensäge :)

ich versuchte gerade deinen Spacereaktor auf einem Raumschiffsboden zu plazieren aber das akzeptiert er nicht. Weltraumplatform und Gerüst I.O. Ist das Absicht?

Ich frag mich nämlich gerade wie ich ein Raumschiff betreiben soll mit dem ich zu den Deepspace Erzfeldern komme ohne Solar. :)

Grüße

Der Flaggi

**Comment by Xman1109** [comment]
Ok, komisch.
Ich hab da eine vorgefertigte Kollisionsmaske von Earendel benutzt, es scheint dann wohl so als ob das nicht mit drin ist, dann werde ich mir das bald Mal angucken.

Update könnte aber ne Weile dauern, es sei denn ich mach ne neue branch für dafür.

Ich arbeite gerade noch an den Brennstäben, da hab ich mir sie Textur aus Ner anderen Mod geholt xD (mit Erlaubnis natürlich)

**Comment by Flagran** [comment]
Hey, ist okay brauch nicht sofort sein, da ich noch am layout arbeite kann ich das als freespace erstmal leerlasesn :)

**Comment by Xman1109** [comment]
sooooo, sollte jetzt gefixt sein, andernfalls nochmal bescheidsagen

**Comment by Flagran** [comment]
> sooooo, sollte jetzt gefixt sein, andernfalls nochmal bescheidsagen

Getestet Läuft. *sich an die Brennstoffzellen macht* :) Dankö

**Comment by Xman1109** [comment]
Gern geschehen :D
