### ISSUE TITLE
Graphite Fuel Cell Fuel Value

### ISSUE THREAD

**Issue by UNOwenWasMe** [Xman1109/Atomic_Overhaul#34]
I understand it is your intention to replace graphite with something else in the future, but as it stands I believe the fuel value of Graphite Fuel cells is much higher than you intended. It is currently worth 19GJ.

The reason why is because to make 1 piece of graphite to you need ~3.33 coal. 1 piece of coal is worth 4MJ, so 1 piece of graphite (while non-burnable in itself, but bear with me), is ~14MJ. Then you need 10 graphite to make 1 graphite fuel cell, which would mean 1 Fuel Cell should be worth around 140MJ, which is 0.14GJ.

So The current fuel value is much higher by a factor of over 100. 
I do like the idea of gaining some extra energy through the process, but I think you added in a few too many zeroes when adding in the fuel value in the code.

While I'm at it, the recipe for the graphite fuel cell requires 10 empty fuel cells, but only produces 1 fuel cell. This is odd.

Maybe it was your intention to be able to bulk produce the fuel cells? In any case, there's some wonky stuff going on and I wanted to let you know.

I hope this was of any help to you! I'm liking the mod a lot so far.

**Comment by Xman1109** [comment]
This is very odd indeed...
The Graphite fuel cells are only accessible with the "old graphite fuel" setting enabled, the recipe will of course be changed, but I looked at the code of the fuel cell, and it should have much less fuel value than that... So my guess is that an external mod modifies that fuel value. So I would need your modlist to look into this further.
But overall, thanks for letting me know!

**Comment by UNOwenWasMe** [comment]
I see! I did check the code myself just now and you are completely right. I should have done that to begin with, my apologies!

After testing out I have found out that the culprit must be Krastorio 2. When I start up the game with just K2 and Atomic Overhaul, the weird stuff happens. In any other configuration the fuel values and recipes are as they should be.

I tested this with the latest versions of both AO and K2.

I have been looking in the files and scripts of K2 but I can't find anything that could cause something weird like this. I will be looking further and if I find something I will definitely let you know.

In the meantime I'll probably overwrite the item values and recipes to their intended state by writing a hacky private mod.

**Comment by Xman1109** [comment]
Yes I saw, I made it that back in the days when I was making AO compatible with K2.
K2 multiplied the fuel value by 6.3 and changed the result of that recipe to only 1 single fuel cell.
I will push my fix for that soon. You will get 10 Fuel cells and the fuel values won't be modified.
