### ISSUE TITLE
[Bug-Report]Failed to load a migrating save with Space Exploration integration enabled

### ISSUE THREAD

**Issue by Vascar** [Xman1109/Atomic_Overhaul#35]
# Bug Report

## Describe the bug

Loading a save with the latest update for the first time accidently had the Space Exploration integration enabled in a mod pack with out Space Exploration. Load fails with this error:

Error while applying migration: Atomic Overhaul: 1.3.15.lua

__Atomic_Overhaul__/migrations/1.3.15.lua:20: attempt to index field 'iridium-192-processing' (a nil value)
stack traceback:
	__Atomic_Overhaul__/migrations/1.3.15.lua:20: in main chunk

## How to reproduce

Have a old save (pre 1.3.15) with the Space Exploration integration enabled but no Space Exploration. Try to load it with 1.3.15.

## Your Idea on how to fix it

In the file "...\migrations\1.3.15.lua",  add a if statement either before or after line 19 that reads something like
if mods["space-exploration"] then

**Comment by Vascar** [comment]
If others have encountered this bug. You can disable the SE integration to load your save.

**Comment by Xman1109** [comment]
I knew something was off, thanks for pointing it out to me!

I've pushed an update to the modportal which should fix it.
