### ISSUE TITLE
[Bug-Report] [1.3.19] Massive increase in max script update time after updating

### ISSUE THREAD

**Issue by Bluebottle39** [Xman1109/Atomic_Overhaul#40]
# Bug Report

- [ ] old graphite fuel setting enabled ?
No

## Describe the bug

Updating from version 1.3.18 to 1.3.19 has massively increased the max script update time. Average and min time very low though. Manifests as lag spikes.

## How to reproduce

just update version. When i downgrade the problem goes away

## Additional information

I am using a pretty big mod list

![factorio_3tTZXGLvCC](https://github.com/Xman1109/Atomic_Overhaul/assets/56110672/5c35fe66-a060-402d-817e-3e0885ed7c83)

Exported mod list from modmyfactory2
[testing.fmp.txt](https://github.com/Xman1109/Atomic_Overhaul/files/12061648/testing.fmp.txt)

If you need any other information I will add

**Comment by Xman1109** [comment]
I know what's causing this, but the people on the factorio discord told me this wouldn't be a big issue.
I will fix it by tomorrow or Monday.

Thanks for informing me about this.

**Comment by Bluebottle39** [comment]
Thank you for the very fast responce!
Thank you for all the work on the mod, love it!

**Comment by Xman1109** [comment]
I updated the mod to include a setting named " Heat Accumulator script " if it gets turned off then the lag spikes should vanish, so let me know.

**Comment by Bluebottle39** [comment]
That works for me. 
Will the heat accumulators still work without the script? What does it do?

**Comment by Xman1109** [comment]
Glad it worked!

The heat accumulator checks every 10 seconds if a coated fluid tank is on a surface and if it has over 24500 Units of heating oil in it, if so the script will convert it into heat accumulator, which does what is says.

**Comment by Bluebottle39** [comment]
Sounds like they won't work without the script then?

in any case thanks for the fix, it's much appreciated!

**Comment by Xman1109** [comment]
Well, I've made it so that you can craft everything, it just does not have its functionality.
But you can fill some tanks and restart the game with this setting on, so that it converts it to a heat accumulator, then restart with the script turned off.

The way it is now is just a temporary solution. I may change it in the future, for example with a command, so it only checks 1 time after executing it, or maybe a recipe to fill the tank if the setting is turned off.

**Comment by Bluebottle39** [comment]
Wonderful, thanks for the clarification.
I'm happy to close this issue now if you are?
