### ISSUE TITLE
[Bug-Report] MOX fuel cell recipe in wrong building 

### ISSUE THREAD

**Issue by GeneralTanker** [Xman1109/Atomic_Overhaul#47]
The MOX-fuel-cell-recipe is showing up in the assembly machine not the centrifuge. 

The fix appears to uncomment the category = "centrifuging" in the MOX-fuel-cell-recipe.lua file.

**Comment by garrotte13** [comment]
The thing is that in Factorio game all nuclear fuel cells are produced in assembly machines, not in centrifuges. And that is correct, because centrifuges are used for separation of matters with different physical properties, not for assembling cells.
