### ISSUE TITLE
Missing Centrifuge

### ISSUE THREAD

**Issue by Bigman0007** [Xman1109/Atomic_Overhaul#52]
# Bug Report

- [ ] old graphite fuel setting enabled ?

## Describe the bug
I have just downloaded the mod. I have started to research the new items. However now i can build any more Centrifuges. I have them researched, but they have disappeared off the my build menu.
```

```

## How to reproduce

```

```

## Your Idea on how to fix it

Maybe i have to restart the game ?
![No Centrifuge](https://github.com/Xman1109/Atomic_Overhaul/assets/159972718/f8a40f98-891b-4175-bd92-3cf4f62db4cb)
![No Centrifuge](https://github.com/Xman1109/Atomic_Overhaul/assets/159972718/984367e5-a02c-4228-9846-258baa8a8f42)

```
![No Centrifuge](https://github.com/Xman1109/Atomic_Overhaul/assets/159972718/800ce965-64a5-48e1-abca-f4c94c800732)


```

## Additional information

```

```

**Comment by Xman1109** [comment]
Ok, that's weird.

Do you use any other mods?

**Comment by Bigman0007** [comment]
![No Centrifuge2](https://github.com/Xman1109/Atomic_Overhaul/assets/159972718/19d0b4c8-393f-4657-b27f-c9946b047b70)


Im not sure why. im going to restart the game. Dont really want to . See if that works.

**Comment by Bigman0007** [comment]
I started a new game and it all seams to be working now.
