### ISSUE TITLE
[Game Crash] After latest update. Not when starting the game, but when loading a save.

### ISSUE THREAD

**Issue by djubre7** [Xman1109/Atomic_Overhaul#53]
# Mod Crashed Game

## Your factorio-current.log / error message screenshot

[factorio-current.log](https://github.com/Xman1109/Atomic_Overhaul/files/14730822/factorio-current.log)

## A list of Mods you are playing with (mod-list.json / written out list)

[mod-list.json](https://github.com/Xman1109/Atomic_Overhaul/files/14730821/mod-list.json)

## Your Idea why it crashed?

Latest update.

## Additional Information

Game does not crash at start, but when trying to load a save. It starts to load, then returns to the main menu with the error message:
"Function 4: function must be a function but is a table
stack traceback:
	[C]: in function 'add_interface'
	__Atomic_Overhaul__/scripts/remote-interface.lua:2: in main chunk
	[C]: in function 'require'
	__Atomic_Overhaul__/control.lua:46: in main chunk"

**Comment by caspaas** [comment]
same here! but with starting a new game AND loading a save
