### ISSUE TITLE
[Bug-Report] Issues with extra modules (thorium 4+)

### ISSUE THREAD

**Issue by Bluebottle39** [Xman1109/Atomic_Overhaul#62]
# Bug Report

- [ ] old graphite fuel setting enabled ?
No

## Describe the bug
Modules (thorium tier 4+) only apply to a very limited selection of recipes and are not detected by mods like module inserter simplified

## How to reproduce
Load game with this mod and space exploration + recipe book
check recipe book for what they can affect

Tier 3 applies to 66 recipes
![tier 3](https://github.com/user-attachments/assets/ea897463-8e31-44ed-8fda-4471fecb6eaa)

Tier 4 applies to only 40 recipes
![tier 4](https://github.com/user-attachments/assets/e4276107-9c03-4086-bef2-96760b0146b5)

## Your Idea on how to fix it
After some time testing it seems that its load order related. The issue seems to be with adding the items in the final fixes phase does not allow other mods to recognise them. 
As an experiment I tried moving the whole space ex section from final fixes to data-updates and it works as expected.
![image](https://github.com/user-attachments/assets/a8b7935f-7a11-44f4-9a1e-1a98f27f1cfa)d

I can submit a pull request if you want but since I am not very familiar with factorio modding I don't know if this solution could have any negative consequences.

## Additional information
Finally, the reason there are more recipes with the t4 than t3 after the fix is because tiers 1-3 use the "thorium_module_limitation" and tiers 4-9 use productivity_module_limitation.
Considering setting them all to thorium_module_limitation in my game for consistency.

**Comment by Xman1109** [comment]
I updated the mod, module 4-9 now use the thorium-module-limitation, instead of the productivity-module-limitation.
This seems to fix all the problems, but if there are any recipes where you think the thorium module should be used, then let me know.

The new version is already on the portal

**Comment by Bluebottle39** [comment]
Hello Xman unfortunately this did not fix my issue

Module inserter simplified does not detect the new modules:
![factorio_PIRMdLp0TK](https://github.com/user-attachments/assets/6f04e9e4-6b3c-404d-89c6-b2e671b94bdb)

And thorium 4+ only works in 9 recipes:
![factorio_d8F2rUJmT9](https://github.com/user-attachments/assets/e9232d4d-99e2-4d14-8a54-d1230380086f)

This part that clued me into the load order issue was that space ex does not modify them:
![factorio_MH1FJooc1Q](https://github.com/user-attachments/assets/da10b065-f97b-49f9-be58-fd58b8362172)
![factorio_qPjdThXRsN](https://github.com/user-attachments/assets/db55680f-ebc2-487e-89c8-7c039f1e7d55)

WIth the change I suggested before and the thorium limitation i get the expected 66 recipes on thorium 4+

**Comment by Xman1109** [comment]
![image](https://github.com/user-attachments/assets/dac160b2-cacc-4f3b-8aad-9fdf9a3e4305)

**Comment by Xman1109** [comment]
Should be working now, I'll upload the update in a couple of minutes
