### ISSUE TITLE
error loading mods with kastorio 2

### ISSUE THREAD

**Issue by lawfulrocky** [Xman1109/Atomic_Overhaul#7]
![Screenshot (8)](https://user-images.githubusercontent.com/25673245/178106995-bbd8f084-7d04-436e-b622-d81fa1cbe80b.png)
 i am getting this error trying to load it i am on the latest kastorio 2 and space exploration

**Comment by Xman1109** [comment]
Thanks for letting me know, I will fix it in less than 24h, try turning off the Space exploration add-on setting in the Atom Overhaul Mod settings

**Comment by Xman1109** [comment]
Should be fixed now.
