### ISSUE TITLE
[Bug-Report] Smol Icons/Sprites

### ISSUE THREAD

**Issue by afewvowels** [Xman1109/Atomic_Overhaul#73]
# Bug Report

## Describe the bug

All On-Belt item icons are half or quarter sized.

## How to reproduce

Since Space Age / 2.0

## Your Idea on how to fix it

Mipmaps?????

## Additional information

Thanks!

**Comment by Xman1109** [comment]
Fix is on GitHub, but not public yet, it will be on the modportal when Atomic Overhaul 1.4 releases

**Comment by afewvowels** [comment]
Awesome, thanks!
